a=int(input("enter the 1st number"))
b=int(input("enter the second number"))
print("Sum of the nos is:",a+b)
print("dif of the nos is:",a-b)
print("prod of the nos is:",a*b)
print("quotien is the nos is:",a/b)
print("mod of the nos is:",a%b)
print("floor div of the nos is:",a//b)
print("exp of the nos is:",a**b)
